#!/usr/bin/env sh
compressed_target_dir=.
uncompressed_target_dir=./buildroot
tar_ver=buildroot-2026.02
hash=d54b7ffece06ff28cbb81e28e3de74ea405ca6b77c38fbe8b18fa57bef585f8b
br_tar_available=false

# Todo?
# Unfortunately, the globbing below doesn't work intuitively
# That is, if not expanded into any file, the output is the string with asterisks
is_tar_in_downloads() {
    # Check if tar is somewhere in ~/Downloads and copy it into cwd
    if [ "$br_tar_available" = false ]; then
        echo ~/Downloads/archiwa/${tar_ver}.tar.x*
        tar_path=$(echo ~/Downloads/**/${tar_ver}.tar.xz)
        echo $tar_path
    fi
}

# Check if BR is already downloaded and present in cwd
if [ -f "$compressed_target_dir/${tar_ver}.tar.xz" ]; then
    br_tar_available=true
fi

# Download tar from the web
if [ "$br_tar_available" = false ]; then
    wget -P "$compressed_target_dir" "https://buildroot.org/downloads/${tar_ver}.tar.xz"
fi

# Check if BR is already unpacked
if [ ! -d "$uncompressed_target_dir" ]; then
    echo "$hash" "${compressed_target_dir}/${tar_ver}.tar.xz" | sha256sum -c || return 1
    mkdir "$uncompressed_target_dir" && \
        tar xvf "${tar_ver}.tar.xz" -C "${uncompressed_target_dir}" --strip-components=1
else
    echo "Buildroot directory already exists!"
fi

rm -r "${compressed_target_dir}/${tar_ver}.tar.xz"

# Generate BR/.config using repo's defconfig
# ( cd "$uncompressed_target_dir" && make defconfig BR2_DEFCONFIG=../defconfig )
echo "To load the repo's defconfig file run \`make defconfig BR2_DEFCONFIG=../defconfig\` \
inside BR root directory."
echo "If you just started the project and have no repo's defconfig, load the board's \
defconfig file by running \`make qemu_aarch64_virt_defconfig\` inside BR root directory."

echo "Make sure that defconfig file was properly loaded into BR/.config before starting \
the initial compilation !!!"
